[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std=lib/forge-std/src",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink-brownie-contracts=lib/chainlink-brownie-contracts/contracts",
    "@chainlink/contracts=lib/chainlink/contracts",
]

# Enable optimization
optimizer = true
optimizer_runs = 200

# Gas settings
gas_limit = 9000000
gas_price = 20000000000

# RPC endpoints
[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/eaFy-as1S6Bas2qUGyjLqcN8zqVDXMwD"

# Etherscan for verification
[etherscan]
sepolia = { key = "2YVQ3F7T4KBNBIF3K5X3F8KKAE88X7FPBR" }